# Generated by Django 4.0.3 on 2022-03-20 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jointsDenavit', models.ManyToManyField(blank=True, related_name='screw_list', to='joint.joint_denavit')),
                ('jointsScrew', models.ManyToManyField(blank=True, related_name='screw_list', to='joint.joint_screw')),
                ('points', models.ManyToManyField(blank=True, related_name='listPoints', to='point.point')),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('robots', models.ManyToManyField(to='core.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Robot_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jointsDenavit', models.ManyToManyField(blank=True, related_name='screw_list', to='joint.joint_denavit_user')),
                ('jointsScrew', models.ManyToManyField(blank=True, related_name='screw_list', to='joint.joint_screw_user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('points', models.ManyToManyField(blank=True, related_name='listPoints', to='point.pointuser')),
            ],
        ),
    ]
