# Generated by Django 4.0.3 on 2022-03-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PointDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('orientation_x', models.FloatField(default=0.0)),
                ('orientation_y', models.FloatField(default=0.0)),
                ('orientation_z', models.FloatField(default=0.0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.robotdefault')),
            ],
        ),
        migrations.CreateModel(
            name='JointScrewDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s_x', models.FloatField(default=0.0)),
                ('s_y', models.FloatField(default=0.0)),
                ('s_z', models.FloatField(default=0.0)),
                ('s0_x', models.FloatField(default=0.0)),
                ('s0_y', models.FloatField(default=0.0)),
                ('s0_z', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.robotdefault')),
            ],
        ),
        migrations.CreateModel(
            name='JointDenavitDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alpha', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('d', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.robotdefault')),
            ],
        ),
    ]
