# Generated by Django 4.0.3 on 2022-03-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='jointsDenavit',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='jointsScrew',
        ),
        migrations.RemoveField(
            model_name='robot_user',
            name='jointsDenavit',
        ),
        migrations.RemoveField(
            model_name='robot_user',
            name='jointsScrew',
        ),
    ]
