# Generated by Django 4.0.3 on 2022-03-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint', '0002_joint_joint_user_delete_joint_denavit_and_more'),
        ('core', '0002_remove_robot_jointsdenavit_remove_robot_jointsscrew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='joints',
            field=models.ManyToManyField(blank=True, related_name='joint_list', to='joint.joint'),
        ),
        migrations.AddField(
            model_name='robot_user',
            name='joints',
            field=models.ManyToManyField(blank=True, related_name='joint_list', to='joint.joint_user'),
        ),
    ]
