# Generated by Django 4.0.3 on 2022-03-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_robotdefault_pointdefault_jointscrewdefault_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='jointdenavit',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='jointdenavitdefault',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='jointscrew',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='jointscrewdefault',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='point',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='point',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='pointdefault',
            name='robot',
        ),
    ]
