# Generated by Django 4.0.3 on 2022-03-14 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercustom_remove_jointdenavit_robot_and_more'),
        ('point', '0001_initial'),
        ('joint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='jointDenavit',
            field=models.ManyToManyField(related_name='jointDenavit_robot', to='joint.jointdenavit'),
        ),
        migrations.AddField(
            model_name='robot',
            name='jointScrew',
            field=models.ManyToManyField(related_name='jointScrew_robot', to='joint.jointscrew'),
        ),
        migrations.AddField(
            model_name='robot',
            name='points',
            field=models.ManyToManyField(related_name='point_robot', to='point.point'),
        ),
        migrations.AddField(
            model_name='robotdefault',
            name='jointDenavit',
            field=models.ManyToManyField(related_name='jointDenavitDefault_robot', to='joint.jointdenavitdefault'),
        ),
        migrations.AddField(
            model_name='robotdefault',
            name='jointScrew',
            field=models.ManyToManyField(related_name='jointScrewDefault_robot', to='joint.jointscrewdefault'),
        ),
        migrations.AddField(
            model_name='robotdefault',
            name='points',
            field=models.ManyToManyField(related_name='pointDefault_robot', to='point.pointdefault'),
        ),
        migrations.DeleteModel(
            name='JointDenavit',
        ),
        migrations.DeleteModel(
            name='JointDenavitDefault',
        ),
        migrations.DeleteModel(
            name='JointScrew',
        ),
        migrations.DeleteModel(
            name='JointScrewDefault',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='PointDefault',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='robots',
            field=models.ManyToManyField(to='core.robot'),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
