# Generated by Django 4.0.3 on 2022-03-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint', '0001_initial'),
        ('point', '0001_initial'),
        ('core', '0004_robot_jointdenavit_robot_jointscrew_robot_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='jointDenavit',
            field=models.ManyToManyField(blank=True, null=True, related_name='jointDenavit_robot', to='joint.jointdenavit'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='jointScrew',
            field=models.ManyToManyField(blank=True, null=True, related_name='jointScrew_robot', to='joint.jointscrew'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, related_name='point_robot', to='point.point'),
        ),
        migrations.AlterField(
            model_name='robotdefault',
            name='jointDenavit',
            field=models.ManyToManyField(blank=True, null=True, related_name='jointDenavitDefault_robot', to='joint.jointdenavitdefault'),
        ),
        migrations.AlterField(
            model_name='robotdefault',
            name='jointScrew',
            field=models.ManyToManyField(blank=True, null=True, related_name='jointScrewDefault_robot', to='joint.jointscrewdefault'),
        ),
        migrations.AlterField(
            model_name='robotdefault',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, related_name='pointDefault_robot', to='point.pointdefault'),
        ),
    ]
