# Generated by Django 4.0.3 on 2022-03-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joint_Denavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('T', 'translation'), ('R', 'rotation')], default='R', max_length=1)),
                ('alpha', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('d', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Denavit_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('T', 'translation'), ('R', 'rotation')], default='R', max_length=1)),
                ('alpha', models.FloatField(default=0.0)),
                ('a', models.FloatField(default=0.0)),
                ('d', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Screw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('T', 'translation'), ('R', 'rotation')], default='R', max_length=1)),
                ('s_x', models.FloatField(default=0.0)),
                ('s_y', models.FloatField(default=0.0)),
                ('s_z', models.FloatField(default=0.0)),
                ('s0_x', models.FloatField(default=0.0)),
                ('s0_y', models.FloatField(default=0.0)),
                ('s0_z', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Joint_Screw_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('T', 'translation'), ('R', 'rotation')], default='R', max_length=1)),
                ('s_x', models.FloatField(default=0.0)),
                ('s_y', models.FloatField(default=0.0)),
                ('s_z', models.FloatField(default=0.0)),
                ('s0_x', models.FloatField(default=0.0)),
                ('s0_y', models.FloatField(default=0.0)),
                ('s0_z', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
                ('theta', models.FloatField(default=0.0)),
            ],
        ),
    ]
